AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Cloudformation Template

Parameters:
  VpcId:
    Type: String
  Subnets:
    Type: String
  ClusterName:
    Type: String
  ContainerImage:
    Type: String

Resources:
  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ecsTaskExecutionRole-devops-test
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: react-app-task
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities: [FARGATE]
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      ContainerDefinitions:
        - Name: react-app
          Image: !Ref ContainerImage
          PortMappings:
            - ContainerPort: 80
          Essential: true

  Service:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: devops-ecs-test
      Cluster: !Ref ClusterName
      LaunchType: FARGATE
      DesiredCount: 1
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets: !Ref Subnets
      TaskDefinition: !Ref TaskDefinition

Outputs:
  ServiceName:
    Description: ECS Service Name
    Value: !Ref Service
  TaskDefinitionArn:
    Description: Task Definition ARN
    Value: !Ref TaskDefinition
