name: push-docker-image-to-ecr

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  push-to-ecr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push image
        env:
          ECR: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}
        run: |
          TAG=$(date -u +'%Y%m%dT%H%M%SZ')
          docker build -t $ECR:$TAG .
          docker push $ECR:$TAG
          echo "Image pushed: $ECR:$TAG"
